### ISSUE TITLE
geocoding in better-admin

### ISSUE THREAD

**Issue by philcruz** [jointheleague/lets-eat#147]
need to implement geocoding in the better-admin branch when a location is added or updated.

**Comment by philcruz** [comment]
@najclark We have a updateDB function defined in 2 places: /lib/functions.js and /server/main.js.

They appear to be identical. We don't need both, right?

**Comment by najclark** [comment]
We need the one in Meteor.methods, because that method needs to be run on the server. I just left the updateDB function in functions.js because I wasn't sure if it was still being used in other places. I was planning on finding where the updateDB function was being used and replacing it with Meteor.call('updateDB')
