### ISSUE TITLE
updateDB is not defined in fixtures.js

### ISSUE THREAD

**Issue by Michaelmvv** [jointheleague/lets-eat#34]

**Comment by philcruz** [comment]
This problem is due to the fact that updateDB() is not defined at the time the code in fixtures.js is run.

Check this SO on the load order 
http://stackoverflow.com/questions/10109176/ordering-of-the-css-and-js-files-loaded-by-meteor

Try moving the updateDB to a file that will load before fixtures.js is run.

**Comment by philcruz** [comment]
Controlling load order by file/directory names has it's downsides and is one criticism against Meteor. 

Today they just released Meteor 1.3. Among other things, they introduced a way to explicitly import files and control load order. This is discussed in the new Meteor guide http://guide.meteor.com/structure.html

So there are a couple of ways to deal with this bug depending on if you are using Meteor 1.2 or 1.3. I'm fine updating to 1.3.
